# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: buildGoApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:


  build:

    matrix:
      go-version: [ 1.18.x, 1.19.x ]
      os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Lint Go Code
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        go get -u golang.org/x/lint/golint
        make lint

    - name: Build
      run: go build -o bin/cobra-cli-test main.go 

    - name: Test
      run: go test -v ./...
